"""Godot project structure auditor.

Verify that a Godot project layout matches the conventions defined in
CLAUDE.md section 12 (scenes/ and scripts/ mirroring, components/
separation) and report asset naming issues, orphan companion files,
suspicious duplicates, and backup leftovers.

The tool is read-only: it never modifies the filesystem.

Requires Python 3.14+ and uses :mod:`cli_toolkit` for Rich output and the
split ``-h`` / ``--help`` behaviour.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from collections import defaultdict
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Final

from cli_toolkit import OutputHandler, build_parser

from godot_audit import __version__

# ===================================================================
# Type aliases (PEP 695)
# ===================================================================


type IssueList = list["Issue"]
type GroupedIssues = dict[str, IssueList]
type SeverityCounts = dict[str, int]


# ===================================================================
# Constants
# ===================================================================


VERSION: Final[str] = __version__

# Directories skipped during traversal (aligned with CLAUDE.md section 0)
DEFAULT_IGNORED_DIRS: Final[frozenset[str]] = frozenset(
    {
        ".godot",
        ".git",
        ".claude",
        "android",
        "export",
        "keystore",
        "node_modules",
        "__pycache__",
        ".vscode",
        ".idea",
    }
)

# File extensions, grouped by role
SCRIPT_EXTS: Final[frozenset[str]] = frozenset({".gd"})
SCENE_EXTS: Final[frozenset[str]] = frozenset({".tscn", ".scn"})
SHADER_EXTS: Final[frozenset[str]] = frozenset({".gdshader", ".gdshaderinc"})
RESOURCE_EXTS: Final[frozenset[str]] = frozenset({".tres", ".res"})
IMAGE_EXTS: Final[frozenset[str]] = frozenset(
    {".png", ".jpg", ".jpeg", ".webp", ".svg", ".gif", ".bmp"}
)
AUDIO_EXTS: Final[frozenset[str]] = frozenset({".mp3", ".wav", ".ogg", ".flac"})
FONT_EXTS: Final[frozenset[str]] = frozenset({".ttf", ".otf", ".woff", ".woff2"})
SOURCE_ART_EXTS: Final[frozenset[str]] = frozenset(
    {".aseprite", ".ase", ".psd", ".kra"}
)

# Companion files regenerated by Godot that reference a source file
COMPANION_SUFFIXES: Final[frozenset[str]] = frozenset({".uid", ".import"})

# Filename suffixes considered stale versions
SUSPICIOUS_STEM_SUFFIXES: Final[tuple[str, ...]] = (
    "_old",
    "_bak",
    "_backup",
    "_copy",
    "_tmp",
    "_temp",
    "_new",
    "_todelete",
    "_deprecated",
)

# Backup-style name patterns
BACKUP_NAME_PATTERNS: Final[tuple[re.Pattern[str], ...]] = (
    re.compile(r"\.bak(\.|$)"),
    re.compile(r"\.orig(\.|$)"),
    re.compile(r"~$"),
)

# Canonical snake_case pattern for stems. Strict variant: only lowercase
# alphanumerics separated by single underscores.
SNAKE_CASE_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-z0-9]+(?:_[a-z0-9]+)*$")

# Extended variant used when ``allow_dashes=True`` (default on
# ``ProjectAuditor``). Accepts a single ``-`` as an in-word separator,
# because Godot asset packs and many font families ship stems like
# ``pixel_operator8-bold`` that are already unambiguous and that
# Godot's importer handles without issue.
SNAKE_CASE_WITH_DASH_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"^[a-z0-9]+(?:[_-][a-z0-9]+)*$"
)

# Extensions subject to snake_case enforcement
SNAKE_CASE_ENFORCED_EXTS: Final[frozenset[str]] = (
    SCRIPT_EXTS
    | SCENE_EXTS
    | SHADER_EXTS
    | RESOURCE_EXTS
    | IMAGE_EXTS
    | AUDIO_EXTS
    | FONT_EXTS
    | SOURCE_ART_EXTS
)

# Default similarity threshold for near-duplicate detection (0.0 - 1.0)
DEFAULT_SIMILARITY_THRESHOLD: Final[float] = 0.88

# Exit codes
EXIT_OK: Final[int] = 0
EXIT_ISSUES_FOUND: Final[int] = 1
EXIT_INVALID_INPUT: Final[int] = 2


# ===================================================================
# Data model
# ===================================================================


class Severity(StrEnum):
    """Severity ranking for issues, used for filtering and sorting."""

    ERROR = "ERROR"
    WARNING = "WARN"
    INFO = "INFO"


class Category(StrEnum):
    """Check categories. Also used as CLI filter values."""

    MIRRORING = "mirroring"
    NAMING = "naming"
    STALE_NAME = "stale_name"
    NEAR_DUPLICATE = "near_duplicate"
    BACKUP = "backup"
    ORPHAN_COMPANION = "orphan_companion"


class Layout(StrEnum):
    """Supported project layout conventions.

    The chosen layout drives the :data:`Category.MIRRORING` check.
    """

    #: Scenes and scripts live in separate top-level directories that
    #: mirror each other: ``scenes/entities/slime.tscn`` plus
    #: ``scripts/entities/slime.gd``. This is Godot's default-documented
    #: convention.
    SPLIT = "split"

    #: A scene and its attached script live in the same directory:
    #: ``features/entities/slime.tscn`` plus ``features/entities/slime.gd``.
    #: Preferred for feature-grouped projects.
    COLOCATED = "colocated"


class SummaryPosition(StrEnum):
    """Where the summary panel is rendered relative to the issue tables."""

    #: Summary appears before the category tables (default).
    TOP = "top"

    #: Summary appears after the category tables. Useful when the report
    #: is long and the reader wants to see the final counts without
    #: scrolling back up.
    BOTTOM = "bottom"

    #: Summary is suppressed entirely. Equivalent to ``--quiet``.
    NONE = "none"


# Human-readable description of each category
CATEGORY_DESCRIPTIONS: Final[dict[Category, str]] = {
    Category.MIRRORING: (
        "Scene and its attached script are not organized per the active layout"
    ),
    Category.NAMING: "Filenames that are not snake_case",
    Category.STALE_NAME: (
        "Files ending with _old, _bak, _backup, etc. — promote or delete"
    ),
    Category.NEAR_DUPLICATE: (
        "Pairs of files with near-identical stems (numbered variants excluded) "
        "— confirm which one to keep"
    ),
    Category.BACKUP: "Editor backups (.bak, .orig, ~) — safe to delete",
    Category.ORPHAN_COMPANION: (
        ".uid or .import with no matching source file — safe to delete"
    ),
}

# Stable order for category groups in rendered output
CATEGORY_DISPLAY_ORDER: Final[tuple[Category, ...]] = (
    Category.MIRRORING,
    Category.STALE_NAME,
    Category.NEAR_DUPLICATE,
    Category.BACKUP,
    Category.ORPHAN_COMPANION,
    Category.NAMING,
)

# Severity -> Rich style mapping for table cells
SEVERITY_STYLES: Final[dict[Severity, str]] = {
    Severity.ERROR: "bold red",
    Severity.WARNING: "yellow",
    Severity.INFO: "blue",
}

# Severity rank for comparisons (higher = more severe)
SEVERITY_RANK: Final[dict[str, int]] = {
    Severity.INFO.value: 0,
    Severity.WARNING.value: 1,
    Severity.ERROR.value: 2,
}

# Per-category extra-column definition used by the text and Markdown
# renderers. The table always carries (Sev, Path); the optional third
# column is category-specific so that each row is self-explanatory
# without repeating a long sentence.
#
# * ``(header, field_name)`` — add a single extra column whose cell
#   reads ``getattr(issue, field_name) or ""``.
# * ``None`` — render only (Sev, Path); the category title already
#   carries the meaning (e.g. backup leftovers).
_CATEGORY_EXTRA_COLUMN: Final[dict[Category, tuple[str, str] | None]] = {
    Category.MIRRORING: ("Suggested move", "suggested"),
    Category.NAMING: ("Suggested", "suggested"),
    Category.STALE_NAME: ("Suffix", "detail"),
    Category.NEAR_DUPLICATE: ("Near-identical to", "paired_with"),
    Category.BACKUP: None,
    Category.ORPHAN_COMPANION: ("Missing source", "detail"),
}


@dataclass(frozen=True, slots=True, order=True)
class Issue:
    """Single audit finding.

    Attributes:
        severity: Importance level.
        category: Category the issue belongs to.
        path: Project-relative path (forward slashes).
        message: Human-readable explanation, kept for JSON output and
            for callers that want a ready-made summary line.
        suggested: Category-specific suggestion (snake_case stem for
            :data:`Category.NAMING`, destination path for
            :data:`Category.MIRRORING`). ``None`` when not applicable.
        paired_with: Other path involved in the finding, used by
            :data:`Category.NEAR_DUPLICATE` to name the near-identical
            sibling. ``None`` when not applicable.
        detail: Short category-specific marker — the stale suffix for
            :data:`Category.STALE_NAME`, the missing source filename for
            :data:`Category.ORPHAN_COMPANION`. ``None`` when not
            applicable.
    """

    severity: Severity
    category: Category
    path: str
    message: str
    suggested: str | None = None
    paired_with: str | None = None
    detail: str | None = None


@dataclass(slots=True)
class AuditReport:
    """Aggregated results of a full project audit.

    Attributes:
        project_root: Absolute path of the audited project.
        files_scanned: Number of files inspected after ignore rules.
        issues: Every issue found, in discovery order.
    """

    project_root: Path
    files_scanned: int = 0
    issues: IssueList = field(default_factory=list)

    def add(self, issue: Issue) -> None:
        """Append an issue to the report.

        Args:
            issue: Finding to store.
        """
        self.issues.append(issue)

    def group_by_category(self) -> GroupedIssues:
        """Return issues grouped by their category.

        Returns:
            Mapping from category name to issues in that category.
        """
        groups: GroupedIssues = defaultdict(list)
        for issue in self.issues:
            groups[issue.category.value].append(issue)
        return dict(groups)

    def counts_by_severity(self) -> SeverityCounts:
        """Return the number of issues at each severity level.

        Returns:
            Mapping from severity label to count.
        """
        counts: SeverityCounts = defaultdict(int)
        for issue in self.issues:
            counts[issue.severity.value] += 1
        return dict(counts)


# ===================================================================
# Core auditor
# ===================================================================


class ProjectAuditor:
    """Run structural and naming checks against a Godot project root."""

    def __init__(
        self,
        project_root: Path,
        *,
        layout: Layout = Layout.COLOCATED,
        similarity_threshold: float = DEFAULT_SIMILARITY_THRESHOLD,
        extra_ignored_dirs: Iterable[str] = (),
        allow_dashes: bool = True,
    ) -> None:
        """Initialize the auditor.

        Args:
            project_root: Path to the Godot project root (containing
                ``project.godot``).
            layout: Project layout convention. Drives the
                :data:`Category.MIRRORING` check. ``Layout.SPLIT`` expects
                ``scenes/`` and ``scripts/`` to mirror each other;
                ``Layout.COLOCATED`` expects each scene and its attached
                script to live in the same directory.
            similarity_threshold: Cutoff passed to
                :func:`difflib.get_close_matches` for typo detection.
            extra_ignored_dirs: Additional directory names to skip on top
                of :data:`DEFAULT_IGNORED_DIRS`.
            allow_dashes: When ``True`` (default), filename stems may use
                ``-`` as a separator in addition to ``_``; stems like
                ``pixel_operator8-bold`` pass the snake_case check. When
                ``False``, only strict snake_case is accepted.

        Raises:
            FileNotFoundError: If *project_root* does not exist.
            ValueError: If *project_root* is not a Godot project.
        """
        self.project_root: Path = project_root.resolve()
        if not self.project_root.is_dir():
            raise FileNotFoundError(f"Project root does not exist: {self.project_root}")
        if not (self.project_root / "project.godot").is_file():
            raise ValueError(
                f"No project.godot found in {self.project_root}; "
                f"is this really a Godot project root?"
            )
        self.layout: Layout = layout
        self.similarity_threshold: float = similarity_threshold
        self.allow_dashes: bool = allow_dashes
        self.ignored_dirs: frozenset[str] = frozenset(
            DEFAULT_IGNORED_DIRS | set(extra_ignored_dirs)
        )
        self._report: AuditReport = AuditReport(project_root=self.project_root)

    # ── Public entry point ─────────────────────────────────────

    def run(self) -> AuditReport:
        """Execute every check and return the populated report.

        Returns:
            Fully populated audit report.
        """
        all_files: list[Path] = list(self._iter_project_files())
        self._report.files_scanned = len(all_files)

        self._check_mirroring(all_files)
        self._check_asset_naming(all_files)
        self._check_suspicious_suffixes(all_files)
        self._check_duplicates_and_typos(all_files)
        self._check_orphan_companions(all_files)
        self._check_backup_files(all_files)

        return self._report

    # ── Traversal helpers ──────────────────────────────────────

    def _iter_project_files(self) -> Iterator[Path]:
        """Yield every non-ignored file in the project.

        Yields:
            Absolute paths of files to consider.
        """
        for path in self.project_root.rglob("*"):
            if not path.is_file():
                continue
            if self._is_ignored(path):
                continue
            yield path

    def _is_ignored(self, path: Path) -> bool:
        """Return whether a path lives under an ignored directory.

        Args:
            path: Absolute file path.

        Returns:
            True when any path segment matches an ignored directory name.
        """
        try:
            relative: Path = path.relative_to(self.project_root)
        except ValueError:
            return True
        return any(part in self.ignored_dirs for part in relative.parts)

    def _rel(self, path: Path) -> str:
        """Return a path relative to the project root with forward slashes.

        Args:
            path: Absolute path inside the project.

        Returns:
            Forward-slash relative path string.
        """
        return path.relative_to(self.project_root).as_posix()

    # ── Check 1: scene <-> script mirroring ────────────────────

    def _check_mirroring(self, all_files: list[Path]) -> None:
        """Dispatch the mirroring check according to the active layout.

        Args:
            all_files: Every project file to consider.
        """
        match self.layout:
            case Layout.SPLIT:
                self._check_mirroring_split(all_files)
            case Layout.COLOCATED:
                self._check_mirroring_colocated(all_files)

    def _check_mirroring_split(self, all_files: list[Path]) -> None:
        """Flag scripts at ``scripts/`` root whose scene lives in a subdir.

        Expects the project to follow the :data:`Layout.SPLIT` convention
        (``scenes/`` and ``scripts/`` as parallel trees).

        Args:
            all_files: Every project file to consider.
        """
        scripts_root: Path = self.project_root / "scripts"
        scenes_root: Path = self.project_root / "scenes"
        if not scripts_root.is_dir() or not scenes_root.is_dir():
            return

        # Map scene stem -> list of scenes/<subdir> where it lives
        scene_stem_to_subdirs: dict[str, list[str]] = defaultdict(list)
        for file_path in all_files:
            if file_path.suffix not in SCENE_EXTS:
                continue
            try:
                rel_to_scenes: Path = file_path.relative_to(scenes_root)
            except ValueError:
                continue
            parent: str = rel_to_scenes.parent.as_posix()
            if parent in {".", ""}:
                continue
            scene_stem_to_subdirs[file_path.stem].append(parent)

        for file_path in all_files:
            if file_path.suffix not in SCRIPT_EXTS:
                continue
            try:
                rel_to_scripts: Path = file_path.relative_to(scripts_root)
            except ValueError:
                continue
            if rel_to_scripts.parent.as_posix() not in {".", ""}:
                continue

            matching_subdirs: list[str] = scene_stem_to_subdirs.get(file_path.stem, [])
            if not matching_subdirs:
                continue

            suggestion: str = matching_subdirs[0]
            suggested_path: str = f"scripts/{suggestion}/{file_path.name}"
            self._report.add(
                Issue(
                    severity=Severity.WARNING,
                    category=Category.MIRRORING,
                    path=self._rel(file_path),
                    message=(
                        f"Script sits at scripts/ root but its scene is in "
                        f"scenes/{suggestion}/. Suggested move: "
                        f"{suggested_path} "
                        f"(use Godot's FileSystem drag & drop)."
                    ),
                    suggested=suggested_path,
                )
            )

    def _check_mirroring_colocated(self, all_files: list[Path]) -> None:
        """Flag scripts whose matching scene is in a different directory.

        Expects the project to follow the :data:`Layout.COLOCATED`
        convention (scene and attached script in the same directory).

        A script is flagged when a scene with the same stem exists
        elsewhere in the project. The check skips scripts that have no
        matching scene at all (they are standalone, autoloads,
        components, or base classes) and skips scenes under well-known
        script-only directories like ``autoload/`` and ``components/``.

        Args:
            all_files: Every project file to consider.
        """
        # Directories whose contents are expected to be script-only.
        # A script under one of these is never flagged even if a scene
        # with the same stem happens to exist elsewhere.
        script_only_top_dirs: frozenset[str] = frozenset(
            {"autoload", "components", "addons"}
        )

        # Index scenes by stem -> list of directories containing them.
        # A stem may legitimately appear in several dirs; we'll surface
        # all candidates in the suggestion if that happens.
        scene_stem_to_dirs: dict[str, list[Path]] = defaultdict(list)
        for file_path in all_files:
            if file_path.suffix not in SCENE_EXTS:
                continue
            scene_stem_to_dirs[file_path.stem].append(file_path.parent)

        for file_path in all_files:
            if file_path.suffix not in SCRIPT_EXTS:
                continue

            # Skip scripts under script-only top-level directories.
            try:
                relative: Path = file_path.relative_to(self.project_root)
            except ValueError:
                continue
            if relative.parts and relative.parts[0] in script_only_top_dirs:
                continue

            candidate_dirs: list[Path] = scene_stem_to_dirs.get(file_path.stem, [])
            if not candidate_dirs:
                # No scene with this stem -> probably a standalone/base class
                continue
            if file_path.parent in candidate_dirs:
                # Already colocated with at least one matching scene
                continue

            # Prefer the first candidate as the suggested destination
            target_dir: Path = candidate_dirs[0]
            target_rel: str = target_dir.relative_to(self.project_root).as_posix()
            suggested_path: str = f"{target_rel}/{file_path.name}"
            extra_note: str = ""
            if len(candidate_dirs) > 1:
                others: list[str] = [
                    d.relative_to(self.project_root).as_posix()
                    for d in candidate_dirs[1:]
                ]
                extra_note = (
                    f" (other candidates: {', '.join(others)}; "
                    f"pick the one that matches the attached script)"
                )

            self._report.add(
                Issue(
                    severity=Severity.WARNING,
                    category=Category.MIRRORING,
                    path=self._rel(file_path),
                    message=(
                        f"Script is not colocated with its scene. "
                        f"Suggested move: {suggested_path}"
                        f"{extra_note} "
                        f"(use Godot's FileSystem drag & drop)."
                    ),
                    suggested=suggested_path,
                )
            )

    # ── Check 2: snake_case naming ─────────────────────────────

    def _check_asset_naming(self, all_files: list[Path]) -> None:
        """Flag any file whose stem is not snake_case.

        Args:
            all_files: Every project file to consider.
        """
        for file_path in all_files:
            suffix: str = file_path.suffix.lower()
            if suffix in COMPANION_SUFFIXES:
                continue
            if suffix not in SNAKE_CASE_ENFORCED_EXTS:
                continue
            stem: str = file_path.stem
            if stem.endswith(".bak"):
                continue
            pattern: re.Pattern[str] = (
                SNAKE_CASE_WITH_DASH_PATTERN
                if self.allow_dashes
                else SNAKE_CASE_PATTERN
            )
            if pattern.match(stem):
                continue
            suggested_name: str = f"{_to_snake_case(stem)}{file_path.suffix}"
            self._report.add(
                Issue(
                    severity=Severity.INFO,
                    category=Category.NAMING,
                    path=self._rel(file_path),
                    message=(
                        f"Filename stem '{stem}' is not snake_case. "
                        f"Suggested: '{suggested_name}'."
                    ),
                    suggested=suggested_name,
                )
            )

    # ── Check 3: suspicious suffixes ───────────────────────────

    def _check_suspicious_suffixes(self, all_files: list[Path]) -> None:
        """Flag files whose stem ends with a stale-version suffix.

        Args:
            all_files: Every project file to consider.
        """
        for file_path in all_files:
            if file_path.suffix.lower() in COMPANION_SUFFIXES:
                continue
            stem_lower: str = file_path.stem.lower()
            for suffix in SUSPICIOUS_STEM_SUFFIXES:
                if stem_lower.endswith(suffix):
                    self._report.add(
                        Issue(
                            severity=Severity.WARNING,
                            category=Category.STALE_NAME,
                            path=self._rel(file_path),
                            message=(
                                f"Filename ends with '{suffix}' — looks like a "
                                f"stale version. Promote it or delete it."
                            ),
                            detail=suffix,
                        )
                    )
                    break
                    break

    # ── Check 4: near-duplicate detection ──────────────────────

    def _check_duplicates_and_typos(self, all_files: list[Path]) -> None:
        """Flag file pairs in the same directory with similar stems.

        Pairs that differ only by numeric runs (e.g. ``v1``/``v2``,
        ``Bird Call 1``/``Bird Call 3``) are treated as numbered
        variants and skipped. See :func:`_normalize_stem_for_variant_check`.

        Args:
            all_files: Every project file to consider.
        """
        per_dir: dict[tuple[str, str], list[Path]] = defaultdict(list)
        for file_path in all_files:
            if file_path.suffix.lower() in COMPANION_SUFFIXES:
                continue
            key: tuple[str, str] = (
                file_path.parent.as_posix(),
                file_path.suffix.lower(),
            )
            per_dir[key].append(file_path)

        flagged_pairs: set[tuple[str, str]] = set()

        for files in per_dir.values():
            if len(files) < 2:
                continue
            stems: list[str] = [f.stem for f in files]
            for i, file_a in enumerate(files):
                others: list[tuple[int, str]] = [
                    (j, s) for j, s in enumerate(stems) if j != i
                ]
                if not others:
                    continue
                close: list[str] = difflib.get_close_matches(
                    stems[i],
                    [s for _, s in others],
                    n=3,
                    cutoff=self.similarity_threshold,
                )
                for similar_stem in close:
                    # Resolve similar_stem back to the matching file index
                    # via the (index, stem) pairs above. This is robust to
                    # duplicate stems in the same directory (unlike
                    # list.index which always returns the first match).
                    match_index: int | None = next(
                        (j for j, s in others if s == similar_stem),
                        None,
                    )
                    if match_index is None:
                        continue

                    # Skip numbered-variant pairs: filenames that only
                    # differ by their numeric parts (v1/v2, 01/02, …).
                    if _normalize_stem_for_variant_check(
                        stems[i]
                    ) == _normalize_stem_for_variant_check(similar_stem):
                        continue

                    # Last-line filter: if the stems swap one full word
                    # at an aligned position (e.g. guitar/synth), they
                    # are semantically unrelated assets — skip.
                    if _has_totally_different_word(stems[i], similar_stem):
                        continue

                    rel_a: str = self._rel(file_a)
                    rel_b: str = self._rel(files[match_index])
                    pair: tuple[str, str] = tuple(sorted((rel_a, rel_b)))
                    if pair in flagged_pairs:
                        continue
                    flagged_pairs.add(pair)
                    self._report.add(
                        Issue(
                            severity=Severity.WARNING,
                            category=Category.NEAR_DUPLICATE,
                            path=pair[0],
                            message=(
                                f"Near-identical filename to '{pair[1]}' — "
                                f"possible typo or forgotten copy. Confirm "
                                f"which one to keep."
                            ),
                            paired_with=pair[1],
                        )
                    )

    # ── Check 5: orphan .uid / .import ─────────────────────────

    def _check_orphan_companions(self, all_files: list[Path]) -> None:
        """Flag companion files with no matching source.

        Args:
            all_files: Every project file to consider.
        """
        existing_files: set[Path] = set(all_files)
        for file_path in all_files:
            suffix: str = file_path.suffix.lower()
            if suffix not in COMPANION_SUFFIXES:
                continue
            source: Path = file_path.with_suffix("")
            if source in existing_files:
                continue
            self._report.add(
                Issue(
                    severity=Severity.WARNING,
                    category=Category.ORPHAN_COMPANION,
                    path=self._rel(file_path),
                    message=(
                        f"Companion file has no matching source "
                        f"('{source.name}' not found in the same directory). "
                        f"Safe to delete."
                    ),
                    detail=source.name,
                )
            )

    # ── Check 6: backup files ──────────────────────────────────

    def _check_backup_files(self, all_files: list[Path]) -> None:
        """Flag editor backups, ``.orig`` leftovers, and tilde-suffixed files.

        Args:
            all_files: Every project file to consider.
        """
        for file_path in all_files:
            name: str = file_path.name
            if any(pattern.search(name) for pattern in BACKUP_NAME_PATTERNS):
                self._report.add(
                    Issue(
                        severity=Severity.WARNING,
                        category=Category.BACKUP,
                        path=self._rel(file_path),
                        message="Backup-style file (editor leftover). Safe to delete.",
                    )
                )


# ===================================================================
# Helpers
# ===================================================================


def _to_snake_case(stem: str) -> str:
    """Return a snake_case suggestion for an arbitrary filename stem.

    Heuristic transformation: camelCase boundaries get an underscore,
    everything is lowercased, any run of non-alphanumerics becomes a
    single underscore, and leading/trailing underscores are stripped.

    Args:
        stem: Original filename stem.

    Returns:
        snake_case suggestion. May still need manual review.
    """
    with_camel_split: str = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", stem)
    lowered: str = with_camel_split.lower()
    normalized: str = re.sub(r"[^a-z0-9]+", "_", lowered)
    collapsed: str = re.sub(r"_+", "_", normalized).strip("_")
    return collapsed or "unnamed"


def _normalize_stem_for_variant_check(stem: str) -> str:
    """Return a variant-normalized form of *stem* for duplicate filtering.

    Any run of digits is replaced by a single placeholder token so that
    naming patterns like ``foo_v1`` / ``foo_v2`` / ``foo_v10``, or
    ``Bird Call 1`` / ``Bird Call 3``, collapse onto the same string.
    When the normalized forms of two stems match, the pair is treated
    as a pair of numbered variants of the same asset rather than as a
    near-duplicate typo, and is not flagged.

    The normalization is case-insensitive so that ``V1`` and ``v2``
    also collapse together.

    Args:
        stem: Original filename stem.

    Returns:
        Normalized stem suitable for equality comparison.
    """
    return re.sub(r"\d+", "#", stem.lower())


# Similarity ratio below which two positionally-aligned alphabetic tokens
# are considered "totally different words" (not a typo of each other).
_TOTALLY_DIFFERENT_WORD_RATIO: Final[float] = 0.5


def _has_totally_different_word(
    stem_a: str,
    stem_b: str,
    ratio_cutoff: float = _TOTALLY_DIFFERENT_WORD_RATIO,
) -> bool:
    """Return True if *stem_a* and *stem_b* differ by a full distinct word.

    Last-line filter for near-duplicate detection: even after
    :func:`difflib.get_close_matches` flags two stems as similar and
    :func:`_normalize_stem_for_variant_check` confirms they are not
    numbered variants, the pair can still be semantically unrelated —
    e.g. ``fluttering_breeze_..._with_guitar_1min_20`` vs
    ``fluttering_breeze_..._with_synth_1min_20``. Such pairs share
    most of their stem but swap one full word at a fixed position.

    Algorithm: both stems are tokenised on non-alphanumeric boundaries
    and lowercased. If the two token lists have different lengths, the
    stems are structurally divergent and the caller's existing decision
    is kept (returns ``False``). Otherwise the tokens are compared
    position by position. Purely numeric token differences are ignored
    (already covered by :func:`_normalize_stem_for_variant_check`). For
    alphabetic (or mixed) token pairs, a :class:`difflib.SequenceMatcher`
    ratio below *ratio_cutoff* means the tokens are unrelated words, and
    the stems are reported as truly different.

    Args:
        stem_a: First filename stem.
        stem_b: Second filename stem.
        ratio_cutoff: Similarity threshold; tokens scoring strictly
            below this are considered totally different words.

    Returns:
        ``True`` if at least one pair of aligned tokens is a fully
        distinct word, ``False`` otherwise.
    """
    tokens_a: list[str] = re.findall(r"[A-Za-z0-9]+", stem_a.lower())
    tokens_b: list[str] = re.findall(r"[A-Za-z0-9]+", stem_b.lower())
    if len(tokens_a) != len(tokens_b):
        return False
    for token_a, token_b in zip(tokens_a, tokens_b, strict=True):
        if token_a == token_b:
            continue
        # Pure digit differences are already handled upstream by the
        # numbered-variant normalizer; ignore them here too.
        if token_a.isdigit() and token_b.isdigit():
            continue
        ratio: float = difflib.SequenceMatcher(None, token_a, token_b).ratio()
        if ratio < ratio_cutoff:
            return True
    return False


def _filter_report(
    report: AuditReport,
    categories: list[str] | None,
    min_severity: str,
) -> AuditReport:
    """Return a new report filtered by category and severity.

    Args:
        report: Original report.
        categories: Category values to keep, or None for all.
        min_severity: Minimum severity label to keep.

    Returns:
        Filtered report.
    """
    min_rank: int = SEVERITY_RANK[min_severity]
    filtered: AuditReport = AuditReport(
        project_root=report.project_root,
        files_scanned=report.files_scanned,
    )
    for issue in report.issues:
        if categories is not None and issue.category.value not in categories:
            continue
        if SEVERITY_RANK[issue.severity.value] < min_rank:
            continue
        filtered.add(issue)
    return filtered


# ===================================================================
# Rendering
# ===================================================================


class AuditRenderer:
    """Render an :class:`AuditReport` via :class:`OutputHandler` or to text.

    Uses Rich tables and panels when available, and falls back to plain
    text otherwise (handled internally by :class:`OutputHandler`).
    """

    def __init__(
        self,
        out: OutputHandler,
        *,
        strip_extension_in_suggested: bool = False,
    ) -> None:
        """Initialize the renderer.

        Args:
            out: Output handler configured by the CLI.
            strip_extension_in_suggested: When ``True``, the NAMING
                table's ``Suggested`` column shows only the stem, with
                the file extension removed. This matches the rename
                workflow in Godot's FileSystem dock and in common
                desktop file managers (GNOME Files / Nautilus, Finder,
                Explorer): pressing F2 or double-clicking a filename
                selects only the stem. A full ``foo.ttf`` suggestion
                pasted over that selection would produce ``foo.ttf.ttf``;
                a bare ``foo`` can be pasted directly.
        """
        self.out: OutputHandler = out
        self.strip_extension_in_suggested: bool = strip_extension_in_suggested

    def _format_extra_value(self, category: Category, raw: str) -> str:
        """Return the extra-column value adjusted for display options.

        Currently only :data:`Category.NAMING` honours
        ``strip_extension_in_suggested`` — other categories (mirroring
        target path, orphan source name, stale suffix, near-duplicate
        sibling path) are displayed as-is.

        Args:
            category: Category of the issue whose value is being
                rendered.
            raw: Raw value as stored on the issue.

        Returns:
            Display-ready value.
        """
        if not raw:
            return ""
        if category is Category.NAMING and self.strip_extension_in_suggested:
            # Drop the last '.ext'; keep inner dots if any.
            dot: int = raw.rfind(".")
            if dot > 0:
                return raw[:dot]
        return raw

    # ── Text rendering ─────────────────────────────────────────

    def render_text(
        self,
        report: AuditReport,
        *,
        summary_position: SummaryPosition = SummaryPosition.TOP,
    ) -> None:
        """Render *report* as text (Rich tables when available).

        Args:
            report: Filtered report to render.
            summary_position: Where to place the summary panel relative
                to the category tables. ``NONE`` suppresses the summary.
        """
        if summary_position is SummaryPosition.TOP:
            self._render_summary(report)

        if not report.issues:
            self.out.success("No issues found.")
            # A BOTTOM summary on an empty report still adds value:
            # the reader sees the "0 files scanned" or threshold info.
            if summary_position is SummaryPosition.BOTTOM:
                self._render_summary(report)
            return

        grouped: GroupedIssues = report.group_by_category()
        for category in CATEGORY_DISPLAY_ORDER:
            issues: IssueList = grouped.get(category.value, [])
            if not issues:
                continue
            self._render_category_table(category, sorted(issues))

        if summary_position is SummaryPosition.BOTTOM:
            self._render_summary(report)

    def _render_summary(self, report: AuditReport) -> None:
        """Render the summary panel.

        Args:
            report: Report whose metadata should be shown.
        """
        counts: SeverityCounts = report.counts_by_severity()
        total: int = len(report.issues)

        lines: list[str] = [
            f"Project: {report.project_root}",
            f"Files scanned: {report.files_scanned}",
            f"Total issues: {total}",
        ]
        for severity in (Severity.ERROR, Severity.WARNING, Severity.INFO):
            count: int = counts.get(severity.value, 0)
            lines.append(f"  {severity.value}: {count}")

        panel = self.out.Panel("\n".join(lines), title="Audit summary")
        self.out.rich_print(panel)

    def _render_category_table(
        self,
        category: Category,
        issues: IssueList,
    ) -> None:
        """Render the issues of a given category as a table.

        The table layout is driven by :data:`_CATEGORY_EXTRA_COLUMN`:
        every table has (Sev, Path); a category-specific third column
        (e.g. ``Suggested`` for naming, ``Near-identical to`` for
        near-duplicates) replaces the previously-shared ``Message``
        column so the same long sentence is never repeated row by row.

        Args:
            category: Category being rendered.
            issues: Sorted issues to display.
        """
        title: str = (
            f"{category.value} ({len(issues)}) — {CATEGORY_DESCRIPTIONS[category]}"
        )
        table = self.out.Table(
            title=title,
            title_style="bold cyan",
            show_lines=False,
        )
        table.add_column("Sev", style="bold", width=6, no_wrap=True)
        table.add_column("Path", style="cyan", overflow="fold")

        extra: tuple[str, str] | None = _CATEGORY_EXTRA_COLUMN.get(category)
        if extra is not None:
            table.add_column(extra[0], overflow="fold")

        for issue in issues:
            sev_style: str = SEVERITY_STYLES[issue.severity]
            if self.out.has_rich:
                sev_cell = self.out.Text(issue.severity.value, style=sev_style)
            else:
                sev_cell = issue.severity.value
            if extra is None:
                table.add_row(sev_cell, issue.path)
            else:
                raw: str = getattr(issue, extra[1]) or ""
                value: str = self._format_extra_value(category, raw)
                table.add_row(sev_cell, issue.path, value)

        self.out.rich_print(table)

    # ── Structured rendering ───────────────────────────────────

    @staticmethod
    def render_json(report: AuditReport) -> str:
        """Return the report as a JSON document.

        Each issue carries its ``severity``, ``category``, ``path`` and
        the full ``message``. Category-specific structured fields
        (``suggested``, ``paired_with``, ``detail``) are emitted only
        when set, so downstream consumers can key on them without
        having to parse the human-readable message.

        Args:
            report: Filtered report to serialize.

        Returns:
            JSON-serialized report.
        """
        issues_payload: list[dict[str, object]] = []
        for issue in report.issues:
            entry: dict[str, object] = {
                "severity": issue.severity.value,
                "category": issue.category.value,
                "path": issue.path,
                "message": issue.message,
            }
            if issue.suggested is not None:
                entry["suggested"] = issue.suggested
            if issue.paired_with is not None:
                entry["paired_with"] = issue.paired_with
            if issue.detail is not None:
                entry["detail"] = issue.detail
            issues_payload.append(entry)

        payload: dict[str, object] = {
            "project_root": str(report.project_root),
            "files_scanned": report.files_scanned,
            "counts_by_severity": report.counts_by_severity(),
            "issues": issues_payload,
        }
        return json.dumps(payload, indent=2, ensure_ascii=False)

    def render_markdown(self, report: AuditReport) -> str:
        """Return the report as a Markdown document.

        The per-category tables honour
        :attr:`strip_extension_in_suggested` just like the text
        renderer, so Markdown copies pasted into a PR match what the
        terminal shows.

        Args:
            report: Filtered report to render.

        Returns:
            Markdown text.
        """
        lines: list[str] = [
            f"# Godot project audit — {report.project_root.name}",
            "",
            f"- **Project root**: `{report.project_root}`",
            f"- **Files scanned**: {report.files_scanned}",
            f"- **Total issues**: {len(report.issues)}",
        ]
        counts: SeverityCounts = report.counts_by_severity()
        for severity in (Severity.ERROR, Severity.WARNING, Severity.INFO):
            lines.append(f"  - **{severity.value}**: {counts.get(severity.value, 0)}")
        lines.append("")

        if not report.issues:
            lines.append("_No issues found._")
            return "\n".join(lines) + "\n"

        grouped: GroupedIssues = report.group_by_category()
        for category in CATEGORY_DISPLAY_ORDER:
            issues: IssueList = grouped.get(category.value, [])
            if not issues:
                continue
            lines.append(
                f"## {category.value} ({len(issues)}) — "
                f"{CATEGORY_DESCRIPTIONS[category]}"
            )
            lines.append("")
            extra: tuple[str, str] | None = _CATEGORY_EXTRA_COLUMN.get(category)
            if extra is None:
                lines.append("| Severity | Path |")
                lines.append("| --- | --- |")
                for issue in sorted(issues):
                    lines.append(f"| {issue.severity.value} | `{issue.path}` |")
            else:
                lines.append(f"| Severity | Path | {extra[0]} |")
                lines.append("| --- | --- | --- |")
                for issue in sorted(issues):
                    raw: str = getattr(issue, extra[1]) or ""
                    value: str = self._format_extra_value(category, raw).replace(
                        "|", r"\|"
                    )
                    lines.append(
                        f"| {issue.severity.value} | `{issue.path}` | {value} |"
                    )
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"


# ===================================================================
# CLI help texts
# ===================================================================


_DESCRIPTION: Final[str] = (
    "Audit a Godot project layout against the conventions defined in "
    "CLAUDE.md. Read-only: never modifies any file."
)

_SHORT_HELP: Final[str] = """
godot-audit — Verify a Godot project layout against conventions

USAGE
    godot-audit [PATH] [OPTIONS]

COMMON OPTIONS
    -y, --layout {split,colocated}     Project layout convention
                                       (default: colocated)
    -f, --format {text,json,markdown}  Output format (default: text)
    -c, --category CAT                 Only keep this category (repeatable)
    -s, --severity {INFO,WARN,ERROR}   Minimum severity to report
    -o, --output FILE                  Write output to FILE instead of stdout
    -p, --summary-position {top,bottom,none}  Where to render the summary
                                              panel (default: top)
    -R, --no-rich                      Plain output, no Rich formatting
    -n, --no-color                     Disable ANSI colors
    -S, --strict                       Non-zero exit even on INFO issues
    -q, --quiet                        Hide summary panel (alias for -p none)
    -v, --verbosity {0,1,2,3}          Output verbosity level

NAMING CHECK TUNING
    -k, --no-dashes          Enforce strict snake_case; reject '-' in stems.
                             By default '-' is accepted as a separator
                             (e.g. 'pixel_operator8-bold' passes).
    -x, --suggested-no-ext   Drop '.ext' from the Suggested column. Godot's
                             FileSystem rename (F2) and desktop file managers
                             select the stem only, so a bare 'foo' can be
                             pasted directly whereas 'foo.ttf' would become
                             'foo.ttf.ttf'. Off by default.

INFO
    -l, --list-categories    List all check categories and exit
    -L, --list-ignored-dirs  List directories ignored by default and exit
    -V, --version            Print version and exit
    -h                       Short help (this memo)
    --help                   Full help with examples
"""

_EPILOG: Final[str] = """
PROJECT LAYOUTS
  split       Scenes and scripts live in separate top-level directories that
              mirror each other. Example:
                  scenes/entities/slime.tscn
                  scripts/entities/slime.gd
              Scripts sitting at the root of scripts/ while their scene is in
              a scenes/ subdirectory are flagged.

  colocated   (default) A scene and its attached script live in the same
              directory, typically grouped by feature. Example:
                  features/entities/slime.tscn
                  features/entities/slime.gd
              Scripts whose matching scene exists in a different directory
              are flagged. Scripts under autoload/, components/, and addons/
              are never flagged since they are expected to be script-only.

CATEGORIES
  mirroring         Depends on --layout. See PROJECT LAYOUTS above.
  naming            Filename stem is not snake_case. Affects scripts, scenes,
                    resources, sprites, audio, and fonts. Suggests a
                    snake_case alternative. Severity: INFO.
                    By default stems with a '-' between alphanum runs
                    (e.g. 'pixel_operator8-bold') are accepted; pass
                    --no-dashes to enforce strict snake_case. Use
                    --suggested-no-ext to display suggestions without
                    the file extension so they can be pasted directly
                    into Godot's FileSystem rename (F2 selects the stem
                    only, not the extension).
  stale_name        Filename ends with _old, _bak, _backup, _copy, _tmp,
                    _temp, _new, _todelete, or _deprecated. Promote or delete.
  near_duplicate    Two files in the same directory with very similar stems
                    (similarity >= threshold). Catches typos like skeleton
                    vs skeletton. Pairs that only differ by numeric parts
                    (v1/v2, 01/02, Bird Call 1 / Bird Call 3) are skipped
                    — they are numbered variants, not duplicates. A final
                    word-level filter additionally skips pairs that swap
                    one fully distinct word at an aligned position
                    (e.g. ..._with_guitar_... vs ..._with_synth_...),
                    which are different assets, not typos. Tune
                    with --threshold.
  backup            Editor backups: *.bak, *.bak.*, *.orig, names ending with ~.
  orphan_companion  A *.uid or *.import file whose source (foo.gd, bar.mp3)
                    is missing. Safe to delete.

EXAMPLES
  Full audit of the current directory, colocated layout (default):
      godot-audit

  Audit a project that still uses the split layout:
      godot-audit ~/my_game --layout split

  Audit a specific project, JSON format written to a file:
      godot-audit ~/my_game --format json --output audit.json

  Only mirroring and near-duplicate issues:
      godot-audit . -c mirroring -c near_duplicate

  Skip INFO noise (naming), only keep WARN and above:
      godot-audit . --severity WARN

  CI-friendly run: strict mode, no color, no Rich, quiet:
      godot-audit . --strict --no-color --no-rich --quiet

  Markdown report suitable for a PR comment:
      godot-audit . --format markdown > audit.md

  More sensitive near-duplicate detection:
      godot-audit . --threshold 0.80

  Long report with summary at the bottom (easier to read than scrolling up):
      godot-audit . --summary-position bottom

  Add custom ignored directories on top of the defaults:
      godot-audit . --ignore-dir docs --ignore-dir build_cache

  Strict snake_case only (reject 'pixel_operator8-bold', etc.):
      godot-audit . --no-dashes

  Bare suggestions in the naming table, ready to paste in Godot's F2
  rename (the extension is already preserved by the rename widget):
      godot-audit . --suggested-no-ext

EXIT CODES
  0   No issues at or above the current severity filter.
  1   At least one WARN or ERROR was reported
      (or any INFO when --strict is set).
  2   Invalid input: PATH does not exist or is not a Godot project.

ENVIRONMENT
  NO_COLOR   When set to any value, disables all ANSI colors and Rich
             styling. See https://no-color.org/.
"""


# ===================================================================
# CLI assembly
# ===================================================================


def _build_cli_parser() -> argparse.ArgumentParser:
    """Build the argument parser with split -h / --help.

    Returns:
        Fully configured parser.
    """
    parser: argparse.ArgumentParser = build_parser(
        prog="godot-audit",
        description=_DESCRIPTION,
        epilog=_EPILOG,
        short_help=_SHORT_HELP,
    )

    parser.add_argument(
        "path",
        nargs="?",
        default=Path.cwd(),
        type=Path,
        metavar="PATH",
        help="Path to the Godot project root (default: current directory).",
    )

    # ── Project convention ──
    layout_choices: list[str] = [lay.value for lay in Layout]
    parser.add_argument(
        "-y",
        "--layout",
        choices=layout_choices,
        default=Layout.COLOCATED.value,
        metavar="LAYOUT",
        help=(
            f"Project layout convention (default: "
            f"{Layout.COLOCATED.value}). Drives the mirroring check. "
            f"Choices: {', '.join(layout_choices)}. See --help for details."
        ),
    )

    # ── Output shape ──
    parser.add_argument(
        "-f",
        "--format",
        choices=("text", "json", "markdown"),
        default="text",
        help="Output format (default: text).",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        metavar="FILE",
        help="Write output to FILE instead of stdout.",
    )

    # ── Filtering ──
    category_choices: list[str] = [c.value for c in Category]
    parser.add_argument(
        "-c",
        "--category",
        action="append",
        choices=category_choices,
        default=None,
        metavar="CAT",
        help=(
            f"Only report issues in CAT. Repeatable. Choices: "
            f"{', '.join(category_choices)}."
        ),
    )
    parser.add_argument(
        "-s",
        "--severity",
        choices=tuple(s.value for s in Severity),
        default=Severity.INFO.value,
        metavar="LVL",
        help="Minimum severity to report (default: INFO).",
    )
    parser.add_argument(
        "-t",
        "--threshold",
        type=float,
        default=DEFAULT_SIMILARITY_THRESHOLD,
        metavar="FLOAT",
        help=(
            f"Similarity threshold (0.0-1.0) for near-duplicate detection "
            f"(default: {DEFAULT_SIMILARITY_THRESHOLD})."
        ),
    )
    parser.add_argument(
        "-i",
        "--ignore-dir",
        action="append",
        default=None,
        metavar="DIR",
        help="Add DIR to the ignored directory list. Repeatable.",
    )

    # ── Naming check tuning ──
    parser.add_argument(
        "-k",
        "--no-dashes",
        dest="allow_dashes",
        action="store_false",
        default=True,
        help=(
            "Treat '-' as invalid in filename stems. By default, stems "
            "like 'pixel_operator8-bold' pass the snake_case check, "
            "because dashes are common in font families and asset packs "
            "and Godot imports them without issue. Pass this flag to "
            "enforce strict snake_case (underscores only)."
        ),
    )
    parser.add_argument(
        "-x",
        "--suggested-no-ext",
        dest="suggested_no_ext",
        action="store_true",
        help=(
            "Drop the file extension from the 'Suggested' column of the "
            "naming table. Godot's FileSystem dock and most desktop file "
            "managers (GNOME Files, Finder, Explorer) select only the "
            "stem when renaming with F2 or a double-click on the name; "
            "pasting 'foo.ttf' over that selection produces 'foo.ttf.ttf'. "
            "With this flag the column shows 'foo' instead, ready to "
            "paste directly. Off by default."
        ),
    )

    # ── Behaviour ──
    parser.add_argument(
        "-S",
        "--strict",
        action="store_true",
        help="Exit non-zero if any issue is reported (including INFO).",
    )
    parser.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help=(
            "Hide the summary panel (only show issues). "
            "Alias for '--summary-position none'."
        ),
    )
    summary_choices: list[str] = [sp.value for sp in SummaryPosition]
    parser.add_argument(
        "-p",
        "--summary-position",
        choices=summary_choices,
        default=SummaryPosition.TOP.value,
        metavar="POS",
        help=(
            f"Where to render the summary panel (default: "
            f"{SummaryPosition.TOP.value}). Choices: "
            f"{', '.join(summary_choices)}. Use 'bottom' when reports "
            f"are long enough that the summary should appear after the "
            f"tables. Text mode only; ignored for JSON and Markdown."
        ),
    )

    # ── Display ──
    parser.add_argument(
        "-R",
        "--no-rich",
        action="store_true",
        help="Force plain-text output, no Rich formatting.",
    )
    parser.add_argument(
        "-n",
        "--no-color",
        action="store_true",
        help="Disable ANSI colors.",
    )
    parser.add_argument(
        "-v",
        "--verbosity",
        type=int,
        choices=(0, 1, 2, 3),
        default=1,
        help="Verbosity level: 0=silent, 1=normal, 2=verbose, 3=debug.",
    )

    # ── Info flags ──
    parser.add_argument(
        "-l",
        "--list-categories",
        action="store_true",
        help="List available check categories and exit.",
    )
    parser.add_argument(
        "-L",
        "--list-ignored-dirs",
        action="store_true",
        help="List default ignored directories and exit.",
    )
    parser.add_argument(
        "-V",
        "--version",
        action="version",
        version=f"%(prog)s {VERSION}",
        help="Show program version and exit.",
    )

    return parser


# ===================================================================
# Info-flag handlers
# ===================================================================


def _print_categories(out: OutputHandler) -> None:
    """Print the list of categories with descriptions.

    Args:
        out: Output handler to use for rendering.
    """
    table = out.Table(title="Audit categories", title_style="bold cyan")
    table.add_column("Category", style="bold")
    table.add_column("Description")
    for category in CATEGORY_DISPLAY_ORDER:
        table.add_row(category.value, CATEGORY_DESCRIPTIONS[category])
    out.rich_print(table)


def _print_ignored_dirs(out: OutputHandler) -> None:
    """Print the default ignored directory list.

    Args:
        out: Output handler to use for rendering.
    """
    table = out.Table(title="Default ignored directories", title_style="bold cyan")
    table.add_column("Directory", style="bold")
    for directory in sorted(DEFAULT_IGNORED_DIRS):
        table.add_row(directory)
    out.rich_print(table)


# ===================================================================
# Main orchestration
# ===================================================================


def _run_audit(
    args: argparse.Namespace,
    out: OutputHandler,
) -> int:
    """Execute the audit workflow and render the results.

    Args:
        args: Parsed CLI arguments.
        out: Configured output handler.

    Returns:
        Process exit code.
    """
    extra_ignored: list[str] = list(args.ignore_dir or [])
    layout: Layout = Layout(args.layout)

    try:
        auditor: ProjectAuditor = ProjectAuditor(
            args.path,
            layout=layout,
            similarity_threshold=args.threshold,
            extra_ignored_dirs=extra_ignored,
            allow_dashes=args.allow_dashes,
        )
    except (FileNotFoundError, ValueError) as exc:
        out.error(str(exc))
        return EXIT_INVALID_INPUT

    out.verbose(f"Auditing {auditor.project_root}")
    out.verbose(
        f"Layout={layout.value}, threshold={args.threshold}, "
        f"format={args.format}, min_severity={args.severity}"
    )

    full_report: AuditReport = auditor.run()
    filtered: AuditReport = _filter_report(full_report, args.category, args.severity)

    _dispatch_render(
        filtered,
        out=out,
        fmt=args.format,
        output_path=args.output,
        summary_position=_resolve_summary_position(args),
        strip_extension_in_suggested=args.suggested_no_ext,
    )

    return _determine_exit_code(filtered, strict=args.strict)


def _resolve_summary_position(args: argparse.Namespace) -> SummaryPosition:
    """Derive the effective summary position from parsed arguments.

    ``--quiet`` is kept as a convenience alias for
    ``--summary-position none``. When both are passed, ``--quiet`` wins
    because it is the stronger intent (the user explicitly asked for
    no summary).

    Args:
        args: Parsed CLI arguments.

    Returns:
        Resolved summary position.
    """
    if args.quiet:
        return SummaryPosition.NONE
    return SummaryPosition(args.summary_position)


def _dispatch_render(
    report: AuditReport,
    *,
    out: OutputHandler,
    fmt: str,
    output_path: Path | None,
    summary_position: SummaryPosition,
    strip_extension_in_suggested: bool = False,
) -> None:
    """Render *report* according to the requested format and target.

    Text rendering goes through :class:`OutputHandler` (Rich or fallback).
    JSON and Markdown are written to stdout or to *output_path*.

    Args:
        report: Filtered report to render.
        out: Output handler (used for text and status messages).
        fmt: Output format identifier.
        output_path: Optional destination file (None = stdout).
        summary_position: Where to place the summary panel in text mode.
            Ignored for JSON and Markdown formats (which always include
            the summary data in a fixed location).
        strip_extension_in_suggested: Forwarded to the renderer to
            control whether the NAMING table's ``Suggested`` column
            strips the file extension. See
            :class:`AuditRenderer` for the rationale.
    """
    renderer: AuditRenderer = AuditRenderer(
        out,
        strip_extension_in_suggested=strip_extension_in_suggested,
    )

    match fmt:
        case "text":
            if output_path is None:
                renderer.render_text(report, summary_position=summary_position)
            else:
                # For text into a file, write the Markdown view instead:
                # Rich escape sequences would pollute a text file, and
                # JSON is available as a dedicated format anyway.
                output_path.write_text(
                    renderer.render_markdown(report), encoding="utf-8"
                )
                out.success(
                    f"Wrote Markdown report to {output_path} "
                    f"(text into file uses the Markdown view)"
                )
        case "json":
            payload: str = AuditRenderer.render_json(report) + "\n"
            if output_path is None:
                sys.stdout.write(payload)
            else:
                output_path.write_text(payload, encoding="utf-8")
                out.success(f"Wrote JSON report to {output_path}")
        case "markdown":
            payload = renderer.render_markdown(report)
            if output_path is None:
                sys.stdout.write(payload)
            else:
                output_path.write_text(payload, encoding="utf-8")
                out.success(f"Wrote Markdown report to {output_path}")
        case _:
            raise ValueError(f"Unknown format: {fmt}")


def _determine_exit_code(report: AuditReport, *, strict: bool) -> int:
    """Compute the final exit code from a rendered report.

    Args:
        report: Filtered report that was just rendered.
        strict: When True, any INFO issue also triggers a non-zero exit.

    Returns:
        Process exit code.
    """
    if not report.issues:
        return EXIT_OK
    if strict:
        return EXIT_ISSUES_FOUND
    has_warn_or_error: bool = any(
        issue.severity in (Severity.WARNING, Severity.ERROR) for issue in report.issues
    )
    return EXIT_ISSUES_FOUND if has_warn_or_error else EXIT_OK


def main(argv: list[str] | None = None) -> int:
    """Entry point for the CLI.

    Args:
        argv: Optional argument vector (used mainly in tests).

    Returns:
        Process exit code.
    """
    parser: argparse.ArgumentParser = _build_cli_parser()
    args: argparse.Namespace = parser.parse_args(argv)

    out: OutputHandler = OutputHandler(
        verbosity=args.verbosity,
        use_rich=not args.no_rich,
        no_color=args.no_color,
    )

    # Handle info flags first — they bypass the audit entirely
    if args.list_categories:
        _print_categories(out)
        return EXIT_OK
    if args.list_ignored_dirs:
        _print_ignored_dirs(out)
        return EXIT_OK

    return _run_audit(args, out)


if __name__ == "__main__":
    raise SystemExit(main())
